import fs from 'fs'
import path from 'path'
import { routing } from '@/i18n/routing'
import { LESSON_VIDEOS } from '@/content/courses.videos'

const COURSES_DIR = path.join(process.cwd(), 'content', 'courses')
const TRACES_DIR = path.join(process.cwd(), 'public', 'edtrace', 'traces')

/**
 * Course catalogs and traces are generated by edtrace-studio and copied in by
 * its `scripts/sync_web_bundle.py` — never hand-edited here. Catalogs land in
 * `content/courses/<course>.json`, traces in
 * `public/edtrace/traces/<course>/<lang>/<lesson>.json`.
 */
export interface CourseCatalog {
  asset_version: string
  course: { id: string; titles: Record<string, string> }
  languages: { code: string; label: string }[]
  lessons: { id: string; default_step: number; titles: Record<string, string> }[]
  videos: {
    id: string
    section: string
    lessons: string[]
    youtube_ids: Record<string, string>
  }[]
}

/**
 * Which language a visitor actually gets when their own isn't available.
 *
 * The site carries five locales but courses are authored in four — Swahili has
 * no lessons at all yet — so every African locale falls through French before
 * English rather than jumping straight to English. `en` lists `fr` only as a
 * backstop for a hypothetical course that ships without an English version;
 * in practice it never fires.
 */
export const COURSE_FALLBACK: Record<string, string[]> = {
  en: ['en', 'fr'],
  fr: ['fr', 'en'],
  sw: ['sw', 'fr', 'en'],
  ln: ['ln', 'fr', 'en'],
  lua: ['lua', 'fr', 'en'],
}

function fallbackChain(locale: string): string[] {
  return COURSE_FALLBACK[locale] ?? [locale, 'fr', 'en']
}

export function getAllCourses(): CourseCatalog[] {
  if (!fs.existsSync(COURSES_DIR)) return []

  return fs
    .readdirSync(COURSES_DIR)
    .filter((f) => f.endsWith('.json'))
    .map((f) => JSON.parse(fs.readFileSync(path.join(COURSES_DIR, f), 'utf-8')) as CourseCatalog)
    .sort((a, b) => a.course.id.localeCompare(b.course.id))
}

export function getCourse(courseId: string): CourseCatalog | null {
  const filePath = path.join(COURSES_DIR, `${courseId}.json`)
  if (!fs.existsSync(filePath)) return null
  return JSON.parse(fs.readFileSync(filePath, 'utf-8')) as CourseCatalog
}

export function getLesson(catalog: CourseCatalog, lessonId: string) {
  return catalog.lessons.find((lesson) => lesson.id === lessonId) ?? null
}

/**
 * Languages a specific lesson can actually be served in.
 *
 * Read from the trace files on disk rather than from `catalog.languages`: the
 * catalog records languages per *course*, so a course whose newest lesson has
 * only been translated into two of its four languages would otherwise advertise
 * links that 404.
 */
export function lessonLanguages(courseId: string, lessonId: string): string[] {
  const dir = path.join(TRACES_DIR, courseId)
  if (!fs.existsSync(dir)) return []

  return fs
    .readdirSync(dir)
    .filter((lang) => fs.existsSync(path.join(dir, lang, `${lessonId}.json`)))
    .sort(
      (a, b) =>
        (routing.locales as readonly string[]).indexOf(a) -
        (routing.locales as readonly string[]).indexOf(b),
    )
}

export interface ResolvedLanguage {
  /** The language actually served. `null` when the lesson exists in none. */
  language: string | null
  /** True when `language` differs from what the visitor asked for. */
  isFallback: boolean
  /** Every language this lesson can be read in, in site-locale order. */
  available: string[]
}

export function resolveLessonLanguage(
  courseId: string,
  lessonId: string,
  locale: string,
): ResolvedLanguage {
  const available = lessonLanguages(courseId, lessonId)
  const language = fallbackChain(locale).find((lang) => available.includes(lang)) ?? null

  return { language, isFallback: language !== null && language !== locale, available }
}

/**
 * Pick a localized string from a `{ en, fr, ln, lua }` map using the same
 * fallback chain, so a title never renders blank for a locale the course
 * doesn't cover.
 */
export function pickLocalized(titles: Record<string, string>, locale: string): string {
  const match = fallbackChain(locale).find((lang) => titles[lang])
  return match ? titles[match] : (Object.values(titles)[0] ?? '')
}

/** Public URL of a lesson's trace, as the viewer will fetch it. */
export function traceUrl(courseId: string, language: string, lessonId: string): string {
  return `/edtrace/traces/${courseId}/${language}/${lessonId}.json`
}

export interface ResolvedVideo {
  videoId: string
  /** Language of the recording — may differ from the lesson text's language. */
  language: string
}

/**
 * The recorded lecture to show above a lesson.
 *
 * Resolved from the language the lesson text is actually being shown in, not
 * from the visitor's locale, so the reader is offered the recording closest to
 * what they are reading. Falls through the same chain, and returns null when no
 * language has a recording yet.
 */
export function resolveLessonVideo(
  courseId: string,
  lessonId: string,
  language: string,
): ResolvedVideo | null {
  const byLanguage = LESSON_VIDEOS[courseId]?.[lessonId]
  if (!byLanguage) return null

  const match = fallbackChain(language).find((lang) => byLanguage[lang])
  return match ? { videoId: byLanguage[match], language: match } : null
}

/** Every (course, lesson) pair, for `generateStaticParams` and the sitemap. */
export function allCourseLessonPairs(): { course: string; lesson: string }[] {
  return getAllCourses().flatMap((catalog) =>
    catalog.lessons.map((lesson) => ({ course: catalog.course.id, lesson: lesson.id })),
  )
}
